//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodBl
{
    using System;
    using System.Collections.Generic;
    
    public partial class Img
    {
        public int ID { get; set; }
        public Nullable<int> DishId { get; set; }
        public byte[] FileStreem { get; set; }
    }
}
